version: 2
updates:
  # Maintain Rust dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Maintain GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Maintain Python dependencies
  - package-ecosystem: "pip"
    directory: "/tests/verify_validate"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
